export const ArticleMap = new Map<string, string>([
  ['bombing-1', 'Wczorajsze popołudnie stało się świadkiem przerażającego aktu terroru na Wall Street, kiedy to potężna eksplozja nagle wstrząsnęła sercem finansowego świata. Eksplozja, która miała miejsce o godzinie 12:01, spowodowała śmierć 30 osób, a ponad 300 zostało rannych.'],
  ['bombing-2', 'Ogromna siła eksplozji spowodowała poważne uszkodzenia budynków w okolicy, w tym siedziby J.P. Morgan & Co., gdzie wielu pracowników doznało obrażeń. Świadkowie mówili o scenerii przypominającej pole bitwy, z ludźmi leżącymi na ulicach i poważnie uszkodzonymi samochodami. Ratownicy i strażacy natychmiast ruszyli na pomoc, próbując zapewnić pierwszą pomoc ofiarom i przeszukując gruzy w poszukiwaniu ocalałych.'],
  ['bombing-3', 'Przyczyna eksplozji nie jest jeszcze dokładnie znana, ale wielu spekuluje, że mogło to być zamach bombowy. Policja Nowego Jorku współpracuje z agentami federalnymi, by ustalić źródło eksplozji i ewentualnych sprawców tego haniebnego czynu. Niektóre wczesne raporty sugerują, że bomba mogła być umieszczona w wozie z końmi, który był zaparkowany w pobliżu miejsca eksplozji.'],
  ['bombing-4', 'Zarówno lokalna społeczność, jak i naród jako całość, są wstrząśnięte tym tragicznym wydarzeniem. Z licznych relacji wynika, że Wall Street, zwykle tętniące życiem i pełne energii, w ciągu kilku sekund zmieniło się w miejsce pełne smutku i chaosu. Władze przysięgły, że uczynią wszystko, co w ich mocy, aby doprowadzić sprawców do odpowiedzialności.'],
  ['story-1-1', '"Pewien młodzieniec zawitał do mojego domu, z propozycją sprzedaży prądu. Jako że jeszcze z mężem nie posiadaliśmy elektryki, zaproponował nam rozwiązanie na dwie umowy, które - zapewnił nas - będzie tańsze niż u Edisonów. Gdy po 3 miesiącach'],
  ['story-1-2', 'do portalu sprawdzić należności, przeżyłam szok! Musiałam zapłacić końcowo o kilka tysięcy więcej, a młodzieniec jak był, tak zniknął." - Grażyna z Pajęczna'],
  ['story-2', '"Śpimy spokojnie z rodziną, u siebie w domu na mazurach. Godzina może druga, trzecia rano - Panie! Hałas! Wpada jaki chłopak odbija się od ściany przy wejściu - ja nie wiem czy mam lecieć po boń czy co - a on że do kibla Panie! I ledwo wbiegł do tego kibla i pół łazienki mi zawymiotował.']
]);
